### PR TITLE
Update game over message

### PR DESCRIPTION
**Pull request by athena-ketabi**
Great!

### CODE REVIEW

**Review by athenaketabi — APPROVED** [review]
Everything is good!

**Review by athenaketabi — APPROVED** [review]

**Review by athenaketabi — APPROVED** [review]
good

**Review by athenaketabi — APPROVED** [review]
good

**Review by athenaketabi — APPROVED** [review]

**Review by athena-ketabi — COMMENTED** [review]
gooood

**Review by athenaketabi — APPROVED** [review]

**Review by athenaketabi — APPROVED** [review]

**Review by athenaketabi — APPROVED** [review]
qwqwqwqw

**Review by athenaketabi — COMMENTED** [review]
I did

**Review by athenaketabi — APPROVED** [review]
I did

**Review by athenaketabi — APPROVED** [review]

**Pull request merged**
